### ISSUE TITLE
大佬，来个选择职位的呀

### ISSUE THREAD

**Issue by restonexyz** [wuranxu/Boss#1]
职位关键词最好设置为可修改的，这样用的行业就多了

**Comment by wuranxu** [comment]
正在做页面版，基于golang 会有以下内容
1. 关键公司过滤
2. 公司地点过滤
3. 自动回复设置(针对不感兴趣公司/心仪公司/黑名单公司)
4. 回复后对方有新消息包含"简历"字样，自动发送附件简历
5. 职位设置

**Comment by wuranxu** [comment]
基本功能已经做好了, 本地没有go环境的话可以下载exe使用。
